data_path: None
task_type: binary

outer_splits: 2
inner_splits: 2
random_state: 42
positive_label: 0

feature_selection: rfecv 
feature_score_tolerance : 0.01
# linear_formula: y ~ C(target, Treatment(reference='control')) + age + C(sex)
# linear_keep_k : 1
# linear_filter_to: target
# linear_alpha: 0.06


model_registry:
  logistic_regression:
    classname: sklearn.linear_model.LogisticRegression
    params:
      max_iter: 5000
      random_state: 42
  decision_tree:
    classname: sklearn.tree.DecisionTreeClassifier
    params:
      random_state: 42
  # Distance-based Models
  knn:
    classname: sklearn.neighbors.KNeighborsClassifier
    params:
      n_jobs: -1
  # Neural Networks
  mlp:
    classname: sklearn.neural_network.MLPClassifier
    params:
      max_iter: 5000
      random_state: 42
      early_stopping: True
      validation_fraction: 0.25

search_spaces:
  logistic_regression:
    C: [0.1, 0.5, 1.0]
    solver: [saga]
    l1_ratio: [0 , 0.2, 0.5, 1]
    
  decision_tree:
    criterion: [gini, entropy]
    splitter: [best, random]
    min_samples_leaf: [1, 5, 10]
    class_weight: [null, balanced]
  # Distance-based
  knn:
    n_neighbors: scipy.stats.randint(1, 11)
    weights: [distance]
    metric: [euclidean, manhattan, minkowski]
  # Neural Networks
  mlp:
    hidden_layer_sizes: scipy.stats.randint(1, 10) 
    activation: [relu, tanh, identity, logistic] 
    solver: [adam, sgd]
    batch_size: [10, 20, 50]
output_dir: ../outputs
